dist: xenial
language: python
python:
  - "3.7"
install:
  - pip install -r requirements-test.txt
  - pip install coveralls
script:
  - pylint examples pyfsm tests
  - flake8 .
  - coverage run --source=slumber setup.py test